[project]
name = 'Biometric-Transaction-System'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.instant-payment-processor]
path = 'contracts/instant-payment-processor.clar'
clarity_version = 3
epoch = 'latest'

[contracts.multi-biometric-authenticator]
path = 'contracts/multi-biometric-authenticator.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
